kind: ConfigMap
apiVersion: v1
metadata:
  name: configmap-nodejs
  namespace: microservices

data:
  PORT: "8081"
  JAVA_SERVICE_URL: http://service-java
  PYTHON_SERVICE_URL: http://service-python


---

kind: ConfigMap
apiVersion: v1
metadata:
  name: configmap-java
  namespace: microservices

data:
  server.port: "8082"
  node.url: http://service-nodejs
  python.url: http://service-python

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: configmap-python
  namespace: microservices

data:
  PORT: "8083"
  NODE_SERVICE_URL: http://service-nodejs
  JAVA_SERVICE_URL: http://service-java
