kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: hpa-nodejs
  namespace: microservices
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: deployment-nodejs
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

--- 

kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: hpa-java
  namespace: microservices
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: deployment-java
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50


---

kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: hpa-python
  namespace: microservices
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: deployment-python
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

