kind: PersistentVolume
apiVersion: v1
metadata:
  name: microservices-pc
  labels:
    type: ssd

spec:
  capacity: 
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /microservices-pv/
    type: DirectoryOrCreate
